# Generated by Django 4.1.4 on 2022-12-20 21:20

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_image_priority_alter_product_base_price_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200)),
                ('video_source', embed_video.fields.EmbedVideoField()),
                ('date_created', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
